import { Package } from 'lucide-react'
import type { SectionDef } from '../types'

export const kitsSection: SectionDef = {
  id: 'kits',
  label: 'Kits',
  icon: Package,
  endpoints: [
    {
      method: 'GET', path: '/api/kits', title: 'List Kit Configs',
      description: 'Returns all kit configurations. Use ?full=true to include full kitData JSON, ?store=true to include storeData.',
      auth: 'bearer', scope: 'kits:read',
      params: [
        { name: 'full', in: 'query', type: 'boolean', required: false, description: 'Include full kitData JSON' },
        { name: 'store', in: 'query', type: 'boolean', required: false, description: 'Include storeData JSON' },
      ],
    },
    {
      method: 'POST', path: '/api/kits', title: 'Create Kit Config',
      description: 'Creates a new kit configuration with name, description, and kitData JSON blob.',
      auth: 'bearer', scope: 'kits:write',
      bodyExample: '{\n  "name": "5x Server Kits",\n  "description": "Kit config for 5x server",\n  "kitData": "{\\"_kits\\":{},\\"_categories\\":{}}"\n}',
    },
    {
      method: 'GET', path: '/api/kits/{id}', title: 'Get Kit Config',
      description: 'Returns a single kit configuration including full kitData and storeData.',
      auth: 'bearer', scope: 'kits:read',
      params: [{ name: 'id', in: 'path', type: 'string', required: true, description: 'Kit config ID (category_...)' }],
    },
    {
      method: 'PUT', path: '/api/kits/{id}', title: 'Update Kit Config',
      description: 'Replaces the name, description, kitData blob, or storeData blob. All fields are optional — only provided fields are updated.',
      auth: 'bearer', scope: 'kits:write',
      params: [{ name: 'id', in: 'path', type: 'string', required: true, description: 'Kit config ID' }],
      bodyExample: '{\n  "name": "5x Server Kits",\n  "kitData": "{\\"_kits\\":{...}}"\n}',
    },
    {
      method: 'DELETE', path: '/api/kits/{id}', title: 'Delete Kit Config',
      description: 'Permanently deletes a kit configuration and all its associated data.',
      auth: 'bearer', scope: 'kits:write',
      params: [{ name: 'id', in: 'path', type: 'string', required: true, description: 'Kit config ID' }],
    },
    {
      method: 'POST', path: '/api/kits/{id}/clone', title: 'Clone Kit Config',
      description: 'Creates a full copy of a kit configuration with a new name. Copies both kitData and storeData.',
      auth: 'bearer', scope: 'kits:write',
      params: [{ name: 'id', in: 'path', type: 'string', required: true, description: 'Source kit config ID' }],
      bodyExample: '{\n  "name": "5x Server Kits (Copy)",\n  "description": "Cloned from 5x"\n}',
    },
    {
      method: 'PATCH', path: '/api/kits/{id}/kit', title: 'Update Kit in Config',
      description: 'Surgically updates any fields on a single kit within a config. Only provided fields are changed — untouched fields are preserved.',
      auth: 'bearer', scope: 'kits:write',
      params: [{ name: 'id', in: 'path', type: 'string', required: true, description: 'Kit config ID' }],
      bodyExample: '{\n  "kitName": "kit_xxx-yyy-zzz",\n  "updates": {\n    "KitImage": "https://cdn.icefuse.com/products/ranks/vip.webp",\n    "Cooldown": 86400\n  }\n}',
    },
    {
      method: 'POST', path: '/api/kits/{id}/kit', title: 'Add Kit to Config',
      description: 'Adds a new kit entry to an existing config. Returns 409 if a kit with that name already exists.',
      auth: 'bearer', scope: 'kits:write',
      params: [{ name: 'id', in: 'path', type: 'string', required: true, description: 'Kit config ID' }],
      bodyExample: '{\n  "kitName": "kit_new-uuid-here",\n  "kit": {\n    "Name": "VIP Kit",\n    "Description": "For VIP players",\n    "RequiredPermission": "kits.vip",\n    "Cooldown": 86400,\n    "MainItems": [],\n    "WearItems": [],\n    "BeltItems": []\n  }\n}',
    },
    {
      method: 'DELETE', path: '/api/kits/{id}/kit', title: 'Remove Kit from Config',
      description: 'Removes a kit from a configuration by its map key. Returns 404 if the kit is not found.',
      auth: 'bearer', scope: 'kits:write',
      params: [{ name: 'id', in: 'path', type: 'string', required: true, description: 'Kit config ID' }],
      bodyExample: '{\n  "kitName": "kit_xxx-yyy-zzz"\n}',
    },
    {
      method: 'GET', path: '/api/kits/{id}/perks', title: 'Get Kit Perks',
      description: 'Returns the PerksData (categories + uncategorized perks) for a specific kit within the config storeData.',
      auth: 'bearer', scope: 'kits:read',
      params: [
        { name: 'id', in: 'path', type: 'string', required: true, description: 'Kit config ID' },
        { name: 'kitId', in: 'query', type: 'string', required: true, description: 'Kit UUID (e.g. kit_xxx)' },
      ],
    },
    {
      method: 'PUT', path: '/api/kits/{id}/perks', title: 'Set Kit Perks',
      description: 'Replaces all perks for a kit. Creates the perks entry if it does not exist.',
      auth: 'bearer', scope: 'kits:write',
      params: [{ name: 'id', in: 'path', type: 'string', required: true, description: 'Kit config ID' }],
      bodyExample: '{\n  "kitId": "kit_xxx-yyy-zzz",\n  "perks": {\n    "categories": [\n      {\n        "id": "cat1",\n        "name": "Combat",\n        "perks": [{ "id": "p1", "text": "+50% damage" }]\n      }\n    ],\n    "uncategorized": [{ "id": "p2", "text": "Free daily kit" }]\n  }\n}',
    },
    {
      method: 'DELETE', path: '/api/kits/{id}/perks', title: 'Remove Kit Perks',
      description: 'Removes all perks for a specified kit. Returns 404 if no perks exist for that kit.',
      auth: 'bearer', scope: 'kits:write',
      params: [{ name: 'id', in: 'path', type: 'string', required: true, description: 'Kit config ID' }],
      bodyExample: '{\n  "kitId": "kit_xxx-yyy-zzz"\n}',
    },
    {
      method: 'GET', path: '/api/kits/{id}/categories', title: 'List Kit Categories',
      description: 'Lists all in-kit categories (top-level groups), sorted by order, with per-category kit counts and nested groups.',
      auth: 'bearer', scope: 'kits:read',
      params: [{ name: 'id', in: 'path', type: 'string', required: true, description: 'Kit config ID' }],
    },
    {
      method: 'POST', path: '/api/kits/{id}/categories', title: 'Create Kit Category',
      description: 'Adds a new top-level category to the kit config. ID uses the uicat_ prefix.',
      auth: 'bearer', scope: 'kits:write',
      params: [{ name: 'id', in: 'path', type: 'string', required: true, description: 'Kit config ID' }],
      bodyExample: '{\n  "name": "VIP Kits",\n  "order": 0\n}',
    },
    {
      method: 'PATCH', path: '/api/kits/{id}/categories', title: 'Update Kit Category',
      description: 'Renames or reorders a category. Supply the catId and any fields to change.',
      auth: 'bearer', scope: 'kits:write',
      params: [{ name: 'id', in: 'path', type: 'string', required: true, description: 'Kit config ID' }],
      bodyExample: '{\n  "catId": "uicat_xxx-yyy",\n  "name": "Premium Kits",\n  "order": 1\n}',
    },
    {
      method: 'DELETE', path: '/api/kits/{id}/categories', title: 'Delete Kit Category',
      description: 'Deletes a category and clears Category/Subcategory from all kits that belonged to it. Returns the number of affected kits.',
      auth: 'bearer', scope: 'kits:write',
      params: [{ name: 'id', in: 'path', type: 'string', required: true, description: 'Kit config ID' }],
      bodyExample: '{\n  "catId": "uicat_xxx-yyy"\n}',
    },
    {
      method: 'GET', path: '/api/kits/{id}/categories/group', title: 'List Kit Groups',
      description: 'Lists all groups (subcategories) within a specific category, sorted by order, with per-group kit counts.',
      auth: 'bearer', scope: 'kits:read',
      params: [
        { name: 'id', in: 'path', type: 'string', required: true, description: 'Kit config ID' },
        { name: 'catId', in: 'query', type: 'string', required: true, description: 'Category ID (uicat_...)' },
      ],
    },
    {
      method: 'POST', path: '/api/kits/{id}/categories/group', title: 'Create Kit Group',
      description: 'Creates a new group (subcategory) within an existing category. ID uses the uisub_ prefix.',
      auth: 'bearer', scope: 'kits:write',
      params: [{ name: 'id', in: 'path', type: 'string', required: true, description: 'Kit config ID' }],
      bodyExample: '{\n  "catId": "uicat_xxx-yyy",\n  "name": "Tier 1",\n  "order": 0\n}',
    },
    {
      method: 'PATCH', path: '/api/kits/{id}/categories/group', title: 'Update Kit Group',
      description: 'Renames or reorders a group within a category.',
      auth: 'bearer', scope: 'kits:write',
      params: [{ name: 'id', in: 'path', type: 'string', required: true, description: 'Kit config ID' }],
      bodyExample: '{\n  "catId": "uicat_xxx-yyy",\n  "groupId": "uisub_aaa-bbb",\n  "name": "Tier 2"\n}',
    },
    {
      method: 'DELETE', path: '/api/kits/{id}/categories/group', title: 'Delete Kit Group',
      description: 'Deletes a group and clears the Subcategory field from all kits that belonged to it.',
      auth: 'bearer', scope: 'kits:write',
      params: [{ name: 'id', in: 'path', type: 'string', required: true, description: 'Kit config ID' }],
      bodyExample: '{\n  "catId": "uicat_xxx-yyy",\n  "groupId": "uisub_aaa-bbb"\n}',
    },
    {
      method: 'POST', path: '/api/kits/sync', title: 'Plugin Sync',
      description: 'Used by the Rust plugin to fetch the current kit config and report kit redemption events back to the server.',
      auth: 'bearer', scope: 'kits:write',
      bodyExample: '{\n  "serverId": "serverid_xxx",\n  "events": [\n    { "kitName": "VIP Kit", "steamId": "76561198...", "timestamp": 1700000000 }\n  ]\n}',
    },
    {
      method: 'GET', path: '/api/kits/mappings', title: 'List Server Mappings',
      description: 'Returns all kit mappings, each including the linked kit config name and server identifier details.',
      auth: 'session',
    },
    {
      method: 'POST', path: '/api/kits/mappings', title: 'Create Server Mapping',
      description: 'Maps a server identifier to a kit config. Optionally sets a live flag and a post-wipe delay in minutes.',
      auth: 'session',
      bodyExample: '{\n  "configId": "category_xxx-yyy",\n  "serverIdentifierId": "serverid_xxx",\n  "isLive": true,\n  "minutesAfterWipe": 0\n}',
    },
    {
      method: 'PATCH', path: '/api/kits/mappings', title: 'Update Server Mapping',
      description: 'Updates an existing mapping by its numeric ID. Any combination of configId, isLive, and minutesAfterWipe can be changed.',
      auth: 'session',
      bodyExample: '{\n  "id": 42,\n  "configId": "category_new-yyy",\n  "isLive": false,\n  "minutesAfterWipe": 30\n}',
    },
    {
      method: 'DELETE', path: '/api/kits/mappings', title: 'Delete Server Mapping',
      description: 'Removes a kit mapping by its numeric ID.',
      auth: 'session',
      bodyExample: '{\n  "id": 42\n}',
    },
  ],
}
