/**
 * Kit Category Management (kitData._categories — top-level groups)
 *
 * GET    /api/kits/[id]/categories         - List all categories with kit counts
 * POST   /api/kits/[id]/categories         - Create a new category
 * PATCH  /api/kits/[id]/categories         - Rename or reorder a category
 * DELETE /api/kits/[id]/categories         - Delete a category (clears assignment on kits)
 *
 * Categories are the first-level visual groupings inside a kit config's kitData._categories.
 * Each category can contain root kits and subcategory groups.
 * Category IDs use the "uicat_" prefix, generated by id.uiCategory().
 */

import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/db'
import { authenticateWithScope } from '@/services/api-auth'
import { auditCreate, auditUpdate, auditDelete } from '@/services/audit'
import {
  kitConfigIdSchema,
  createKitCategorySchema,
  updateKitCategorySchema,
  deleteKitCategorySchema,
} from '@/lib/validations/kit'
import { logger } from '@/lib/logger'
import { parseKitData, stringifyKitData } from '@/lib/utils/kit'
import { id as idGen } from '@/lib/id'
import type { KitsData } from '@/types/kit'

type RouteContext = { params: Promise<{ id: string }> }

/**
 * GET /api/kits/[id]/categories
 * List all categories with per-category kit counts
 */
export async function GET(request: NextRequest, context: RouteContext) {
  const authResult = await authenticateWithScope(request, 'kits:read')

  if (!authResult.success) {
    return NextResponse.json(
      { success: false, error: { code: 'AUTH_ERROR', message: authResult.error } },
      { status: authResult.status }
    )
  }

  try {
    const params = await context.params
    const idParsed = kitConfigIdSchema.safeParse({ id: params.id })

    if (!idParsed.success) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid kit configuration ID' } },
        { status: 400 }
      )
    }

    // PERF: Select only kitData — storeData not needed
    const config = await prisma.kitConfig.findUnique({
      where: { id: idParsed.data.id },
      select: { id: true, kitData: true },
    })

    if (!config) {
      return NextResponse.json(
        { success: false, error: { code: 'NOT_FOUND', message: 'Kit configuration not found' } },
        { status: 404 }
      )
    }

    const kitsData = parseKitData(config.kitData)
    const categories = kitsData._categories ?? {}

    // Build response with kit count per category
    const result = Object.entries(categories)
      .map(([catId, cat]) => {
        const kitCount = Object.values(kitsData._kits).filter(
          (k) => k.Category === catId
        ).length

        const groups = Object.entries(cat.subcategories ?? {})
          .map(([groupId, group]) => ({
            id: groupId,
            name: group.name,
            order: group.order,
            kitCount: Object.values(kitsData._kits).filter(
              (k) => k.Category === catId && k.Subcategory === groupId
            ).length,
          }))
          .sort((a, b) => a.order - b.order)

        return {
          id: catId,
          name: cat.name,
          order: cat.order,
          kitCount,
          groups,
        }
      })
      .sort((a, b) => a.order - b.order)

    return NextResponse.json({ success: true, data: result })
  } catch (error) {
    logger.admin.error('Failed to list kit categories', error as Error)
    return NextResponse.json(
      { success: false, error: { code: 'INTERNAL_ERROR', message: 'Failed to list kit categories' } },
      { status: 500 }
    )
  }
}

/**
 * POST /api/kits/[id]/categories
 * Create a new category; auto-assigns the next order position
 */
export async function POST(request: NextRequest, context: RouteContext) {
  const authResult = await authenticateWithScope(request, 'kits:write')

  if (!authResult.success) {
    return NextResponse.json(
      { success: false, error: { code: 'AUTH_ERROR', message: authResult.error } },
      { status: authResult.status }
    )
  }

  try {
    const params = await context.params
    const idParsed = kitConfigIdSchema.safeParse({ id: params.id })

    if (!idParsed.success) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid kit configuration ID' } },
        { status: 400 }
      )
    }

    const body = await request.json()

    // SECURITY: Zod validated
    const parsed = createKitCategorySchema.safeParse(body)
    if (!parsed.success) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'Validation failed', details: parsed.error.flatten() } },
        { status: 400 }
      )
    }

    const { name, order } = parsed.data

    const existing = await prisma.kitConfig.findUnique({
      where: { id: idParsed.data.id },
      select: { id: true, kitData: true },
    })

    if (!existing) {
      return NextResponse.json(
        { success: false, error: { code: 'NOT_FOUND', message: 'Kit configuration not found' } },
        { status: 404 }
      )
    }

    const kitsData = parseKitData(existing.kitData)
    const categories = kitsData._categories ?? {}

    // Auto-assign order if not provided
    const nextOrder = order ?? Object.keys(categories).length

    const catId = idGen.uiCategory()
    const newCategory = { name, order: nextOrder, subcategories: {} }

    const updatedKitsData: KitsData = {
      ...kitsData,
      _categories: { ...categories, [catId]: newCategory },
    }

    await prisma.kitConfig.update({
      where: { id: idParsed.data.id },
      data: { kitData: stringifyKitData(updatedKitsData) },
    })

    // SECURITY: Audit logged
    await auditCreate(
      'kitCategory',
      `${idParsed.data.id}:${catId}`,
      authResult.context,
      { catId, configId: idParsed.data.id, name, order: nextOrder },
      request
    )

    logger.admin.info('Kit category created', {
      configId: idParsed.data.id,
      catId,
      name,
      actor: authResult.context.actorId,
    })

    return NextResponse.json(
      { success: true, data: { id: catId, name, order: nextOrder, groups: [] } },
      { status: 201 }
    )
  } catch (error) {
    logger.admin.error('Failed to create kit category', error as Error)
    return NextResponse.json(
      { success: false, error: { code: 'INTERNAL_ERROR', message: 'Failed to create kit category' } },
      { status: 500 }
    )
  }
}

/**
 * PATCH /api/kits/[id]/categories
 * Rename and/or reorder an existing category
 */
export async function PATCH(request: NextRequest, context: RouteContext) {
  const authResult = await authenticateWithScope(request, 'kits:write')

  if (!authResult.success) {
    return NextResponse.json(
      { success: false, error: { code: 'AUTH_ERROR', message: authResult.error } },
      { status: authResult.status }
    )
  }

  try {
    const params = await context.params
    const idParsed = kitConfigIdSchema.safeParse({ id: params.id })

    if (!idParsed.success) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid kit configuration ID' } },
        { status: 400 }
      )
    }

    const body = await request.json()

    // SECURITY: Zod validated
    const parsed = updateKitCategorySchema.safeParse(body)
    if (!parsed.success) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'Validation failed', details: parsed.error.flatten() } },
        { status: 400 }
      )
    }

    const { catId, name, order } = parsed.data

    const existing = await prisma.kitConfig.findUnique({
      where: { id: idParsed.data.id },
      select: { id: true, kitData: true },
    })

    if (!existing) {
      return NextResponse.json(
        { success: false, error: { code: 'NOT_FOUND', message: 'Kit configuration not found' } },
        { status: 404 }
      )
    }

    const kitsData = parseKitData(existing.kitData)
    const categories = kitsData._categories ?? {}

    if (!categories[catId]) {
      return NextResponse.json(
        { success: false, error: { code: 'NOT_FOUND', message: `Category "${catId}" not found` } },
        { status: 404 }
      )
    }

    const previousCategory = categories[catId]
    const updatedCategory = {
      ...previousCategory,
      ...(name !== undefined && { name }),
      ...(order !== undefined && { order }),
    }

    const updatedKitsData: KitsData = {
      ...kitsData,
      _categories: { ...categories, [catId]: updatedCategory },
    }

    await prisma.kitConfig.update({
      where: { id: idParsed.data.id },
      data: { kitData: stringifyKitData(updatedKitsData) },
    })

    // SECURITY: Audit logged
    await auditUpdate(
      'kitCategory',
      `${idParsed.data.id}:${catId}`,
      authResult.context,
      { catId, ...previousCategory },
      { catId, ...updatedCategory },
      request
    )

    logger.admin.info('Kit category updated', {
      configId: idParsed.data.id,
      catId,
      actor: authResult.context.actorId,
    })

    return NextResponse.json({ success: true, data: { id: catId, ...updatedCategory } })
  } catch (error) {
    logger.admin.error('Failed to update kit category', error as Error)
    return NextResponse.json(
      { success: false, error: { code: 'INTERNAL_ERROR', message: 'Failed to update kit category' } },
      { status: 500 }
    )
  }
}

/**
 * DELETE /api/kits/[id]/categories
 * Delete a category and clear its assignment from all kits that used it
 */
export async function DELETE(request: NextRequest, context: RouteContext) {
  const authResult = await authenticateWithScope(request, 'kits:write')

  if (!authResult.success) {
    return NextResponse.json(
      { success: false, error: { code: 'AUTH_ERROR', message: authResult.error } },
      { status: authResult.status }
    )
  }

  try {
    const params = await context.params
    const idParsed = kitConfigIdSchema.safeParse({ id: params.id })

    if (!idParsed.success) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid kit configuration ID' } },
        { status: 400 }
      )
    }

    const body = await request.json()

    // SECURITY: Zod validated
    const parsed = deleteKitCategorySchema.safeParse(body)
    if (!parsed.success) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'Validation failed', details: parsed.error.flatten() } },
        { status: 400 }
      )
    }

    const { catId } = parsed.data

    const existing = await prisma.kitConfig.findUnique({
      where: { id: idParsed.data.id },
      select: { id: true, kitData: true },
    })

    if (!existing) {
      return NextResponse.json(
        { success: false, error: { code: 'NOT_FOUND', message: 'Kit configuration not found' } },
        { status: 404 }
      )
    }

    const kitsData = parseKitData(existing.kitData)
    const categories = kitsData._categories ?? {}

    if (!categories[catId]) {
      return NextResponse.json(
        { success: false, error: { code: 'NOT_FOUND', message: `Category "${catId}" not found` } },
        { status: 404 }
      )
    }

    const removedCategory = categories[catId]

    // Remove category from _categories
    const { [catId]: _removed, ...remainingCategories } = categories

    // Clear Category and Subcategory from all kits that belonged to this category
    const updatedKits = { ...kitsData._kits }
    let affectedKitCount = 0
    Object.entries(updatedKits).forEach(([kitId, kit]) => {
      if (kit.Category === catId) {
        updatedKits[kitId] = { ...kit, Category: undefined, Subcategory: undefined }
        affectedKitCount++
      }
    })

    const updatedKitsData: KitsData = {
      ...kitsData,
      _categories: remainingCategories,
      _kits: updatedKits,
    }

    await prisma.kitConfig.update({
      where: { id: idParsed.data.id },
      data: { kitData: stringifyKitData(updatedKitsData) },
    })

    // SECURITY: Audit logged
    await auditDelete(
      'kitCategory',
      `${idParsed.data.id}:${catId}`,
      authResult.context,
      { catId, configId: idParsed.data.id, ...removedCategory, affectedKitCount },
      request
    )

    logger.admin.info('Kit category deleted', {
      configId: idParsed.data.id,
      catId,
      affectedKitCount,
      actor: authResult.context.actorId,
    })

    return NextResponse.json({ success: true, data: { affectedKitCount } })
  } catch (error) {
    logger.admin.error('Failed to delete kit category', error as Error)
    return NextResponse.json(
      { success: false, error: { code: 'INTERNAL_ERROR', message: 'Failed to delete kit category' } },
      { status: 500 }
    )
  }
}
