/**
 * Kit Group Management (kitData._categories[catId].subcategories — second-level groups)
 *
 * GET    /api/kits/[id]/categories/group?catId=<catId>  - List all groups within a category
 * POST   /api/kits/[id]/categories/group                - Create a new group in a category
 * PATCH  /api/kits/[id]/categories/group                - Rename or reorder a group
 * DELETE /api/kits/[id]/categories/group                - Delete a group (clears Subcategory on kits)
 *
 * Groups are the second-level visual groupings (subcategories) within a category.
 * Group IDs use the "uisub_" prefix, generated by id.uiSubcategory().
 */

import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/db'
import { authenticateWithScope } from '@/services/api-auth'
import { auditCreate, auditUpdate, auditDelete } from '@/services/audit'
import {
  kitConfigIdSchema,
  createKitGroupSchema,
  updateKitGroupSchema,
  deleteKitGroupSchema,
} from '@/lib/validations/kit'
import { logger } from '@/lib/logger'
import { parseKitData, stringifyKitData } from '@/lib/utils/kit'
import { id as idGen } from '@/lib/id'
import type { KitsData } from '@/types/kit'

type RouteContext = { params: Promise<{ id: string }> }

/**
 * GET /api/kits/[id]/categories/group?catId=<catId>
 * List all groups within a category, sorted by order, with per-group kit counts
 */
export async function GET(request: NextRequest, context: RouteContext) {
  const authResult = await authenticateWithScope(request, 'kits:read')

  if (!authResult.success) {
    return NextResponse.json(
      { success: false, error: { code: 'AUTH_ERROR', message: authResult.error } },
      { status: authResult.status }
    )
  }

  try {
    const params = await context.params
    const idParsed = kitConfigIdSchema.safeParse({ id: params.id })

    if (!idParsed.success) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid kit configuration ID' } },
        { status: 400 }
      )
    }

    const { searchParams } = new URL(request.url)
    const catId = searchParams.get('catId')

    if (!catId || catId.trim().length === 0) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'catId query parameter is required' } },
        { status: 400 }
      )
    }

    // PERF: Select only kitData
    const config = await prisma.kitConfig.findUnique({
      where: { id: idParsed.data.id },
      select: { id: true, kitData: true },
    })

    if (!config) {
      return NextResponse.json(
        { success: false, error: { code: 'NOT_FOUND', message: 'Kit configuration not found' } },
        { status: 404 }
      )
    }

    const kitsData = parseKitData(config.kitData)
    const category = kitsData._categories?.[catId]

    if (!category) {
      return NextResponse.json(
        { success: false, error: { code: 'NOT_FOUND', message: `Category "${catId}" not found` } },
        { status: 404 }
      )
    }

    const groups = Object.entries(category.subcategories ?? {})
      .map(([groupId, group]) => ({
        id: groupId,
        name: group.name,
        order: group.order,
        kitCount: Object.values(kitsData._kits).filter(
          (k) => k.Category === catId && k.Subcategory === groupId
        ).length,
      }))
      .sort((a, b) => a.order - b.order)

    return NextResponse.json({ success: true, data: { catId, groups } })
  } catch (error) {
    logger.admin.error('Failed to list kit groups', error as Error)
    return NextResponse.json(
      { success: false, error: { code: 'INTERNAL_ERROR', message: 'Failed to list kit groups' } },
      { status: 500 }
    )
  }
}

/**
 * POST /api/kits/[id]/categories/group
 * Create a new group within an existing category
 */
export async function POST(request: NextRequest, context: RouteContext) {
  const authResult = await authenticateWithScope(request, 'kits:write')

  if (!authResult.success) {
    return NextResponse.json(
      { success: false, error: { code: 'AUTH_ERROR', message: authResult.error } },
      { status: authResult.status }
    )
  }

  try {
    const params = await context.params
    const idParsed = kitConfigIdSchema.safeParse({ id: params.id })

    if (!idParsed.success) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid kit configuration ID' } },
        { status: 400 }
      )
    }

    const body = await request.json()

    // SECURITY: Zod validated
    const parsed = createKitGroupSchema.safeParse(body)
    if (!parsed.success) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'Validation failed', details: parsed.error.flatten() } },
        { status: 400 }
      )
    }

    const { catId, name, order } = parsed.data

    const existing = await prisma.kitConfig.findUnique({
      where: { id: idParsed.data.id },
      select: { id: true, kitData: true },
    })

    if (!existing) {
      return NextResponse.json(
        { success: false, error: { code: 'NOT_FOUND', message: 'Kit configuration not found' } },
        { status: 404 }
      )
    }

    const kitsData = parseKitData(existing.kitData)
    const categories = kitsData._categories ?? {}
    const category = categories[catId]

    if (!category) {
      return NextResponse.json(
        { success: false, error: { code: 'NOT_FOUND', message: `Category "${catId}" not found` } },
        { status: 404 }
      )
    }

    const existingGroups = category.subcategories ?? {}
    const nextOrder = order ?? Object.keys(existingGroups).length

    const groupId = idGen.uiSubcategory()
    const newGroup = { name, order: nextOrder }

    const updatedKitsData: KitsData = {
      ...kitsData,
      _categories: {
        ...categories,
        [catId]: {
          ...category,
          subcategories: { ...existingGroups, [groupId]: newGroup },
        },
      },
    }

    await prisma.kitConfig.update({
      where: { id: idParsed.data.id },
      data: { kitData: stringifyKitData(updatedKitsData) },
    })

    // SECURITY: Audit logged
    await auditCreate(
      'kitGroup',
      `${idParsed.data.id}:${catId}:${groupId}`,
      authResult.context,
      { groupId, catId, configId: idParsed.data.id, name, order: nextOrder },
      request
    )

    logger.admin.info('Kit group created', {
      configId: idParsed.data.id,
      catId,
      groupId,
      name,
      actor: authResult.context.actorId,
    })

    return NextResponse.json(
      { success: true, data: { id: groupId, catId, name, order: nextOrder } },
      { status: 201 }
    )
  } catch (error) {
    logger.admin.error('Failed to create kit group', error as Error)
    return NextResponse.json(
      { success: false, error: { code: 'INTERNAL_ERROR', message: 'Failed to create kit group' } },
      { status: 500 }
    )
  }
}

/**
 * PATCH /api/kits/[id]/categories/group
 * Rename and/or reorder an existing group
 */
export async function PATCH(request: NextRequest, context: RouteContext) {
  const authResult = await authenticateWithScope(request, 'kits:write')

  if (!authResult.success) {
    return NextResponse.json(
      { success: false, error: { code: 'AUTH_ERROR', message: authResult.error } },
      { status: authResult.status }
    )
  }

  try {
    const params = await context.params
    const idParsed = kitConfigIdSchema.safeParse({ id: params.id })

    if (!idParsed.success) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid kit configuration ID' } },
        { status: 400 }
      )
    }

    const body = await request.json()

    // SECURITY: Zod validated
    const parsed = updateKitGroupSchema.safeParse(body)
    if (!parsed.success) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'Validation failed', details: parsed.error.flatten() } },
        { status: 400 }
      )
    }

    const { catId, groupId, name, order } = parsed.data

    const existing = await prisma.kitConfig.findUnique({
      where: { id: idParsed.data.id },
      select: { id: true, kitData: true },
    })

    if (!existing) {
      return NextResponse.json(
        { success: false, error: { code: 'NOT_FOUND', message: 'Kit configuration not found' } },
        { status: 404 }
      )
    }

    const kitsData = parseKitData(existing.kitData)
    const categories = kitsData._categories ?? {}
    const category = categories[catId]

    if (!category) {
      return NextResponse.json(
        { success: false, error: { code: 'NOT_FOUND', message: `Category "${catId}" not found` } },
        { status: 404 }
      )
    }

    const groups = category.subcategories ?? {}
    if (!groups[groupId]) {
      return NextResponse.json(
        { success: false, error: { code: 'NOT_FOUND', message: `Group "${groupId}" not found in category "${catId}"` } },
        { status: 404 }
      )
    }

    const previousGroup = groups[groupId]
    const updatedGroup = {
      ...previousGroup,
      ...(name !== undefined && { name }),
      ...(order !== undefined && { order }),
    }

    const updatedKitsData: KitsData = {
      ...kitsData,
      _categories: {
        ...categories,
        [catId]: {
          ...category,
          subcategories: { ...groups, [groupId]: updatedGroup },
        },
      },
    }

    await prisma.kitConfig.update({
      where: { id: idParsed.data.id },
      data: { kitData: stringifyKitData(updatedKitsData) },
    })

    // SECURITY: Audit logged
    await auditUpdate(
      'kitGroup',
      `${idParsed.data.id}:${catId}:${groupId}`,
      authResult.context,
      { groupId, catId, ...previousGroup },
      { groupId, catId, ...updatedGroup },
      request
    )

    logger.admin.info('Kit group updated', {
      configId: idParsed.data.id,
      catId,
      groupId,
      actor: authResult.context.actorId,
    })

    return NextResponse.json({ success: true, data: { id: groupId, catId, ...updatedGroup } })
  } catch (error) {
    logger.admin.error('Failed to update kit group', error as Error)
    return NextResponse.json(
      { success: false, error: { code: 'INTERNAL_ERROR', message: 'Failed to update kit group' } },
      { status: 500 }
    )
  }
}

/**
 * DELETE /api/kits/[id]/categories/group
 * Delete a group and clear its assignment from all kits that used it
 */
export async function DELETE(request: NextRequest, context: RouteContext) {
  const authResult = await authenticateWithScope(request, 'kits:write')

  if (!authResult.success) {
    return NextResponse.json(
      { success: false, error: { code: 'AUTH_ERROR', message: authResult.error } },
      { status: authResult.status }
    )
  }

  try {
    const params = await context.params
    const idParsed = kitConfigIdSchema.safeParse({ id: params.id })

    if (!idParsed.success) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'Invalid kit configuration ID' } },
        { status: 400 }
      )
    }

    const body = await request.json()

    // SECURITY: Zod validated
    const parsed = deleteKitGroupSchema.safeParse(body)
    if (!parsed.success) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'Validation failed', details: parsed.error.flatten() } },
        { status: 400 }
      )
    }

    const { catId, groupId } = parsed.data

    const existing = await prisma.kitConfig.findUnique({
      where: { id: idParsed.data.id },
      select: { id: true, kitData: true },
    })

    if (!existing) {
      return NextResponse.json(
        { success: false, error: { code: 'NOT_FOUND', message: 'Kit configuration not found' } },
        { status: 404 }
      )
    }

    const kitsData = parseKitData(existing.kitData)
    const categories = kitsData._categories ?? {}
    const category = categories[catId]

    if (!category) {
      return NextResponse.json(
        { success: false, error: { code: 'NOT_FOUND', message: `Category "${catId}" not found` } },
        { status: 404 }
      )
    }

    const groups = category.subcategories ?? {}
    if (!groups[groupId]) {
      return NextResponse.json(
        { success: false, error: { code: 'NOT_FOUND', message: `Group "${groupId}" not found in category "${catId}"` } },
        { status: 404 }
      )
    }

    const removedGroup = groups[groupId]
    const { [groupId]: _removed, ...remainingGroups } = groups

    // Clear Subcategory from all kits that belonged to this group
    const updatedKits = { ...kitsData._kits }
    let affectedKitCount = 0
    Object.entries(updatedKits).forEach(([kitId, kit]) => {
      if (kit.Category === catId && kit.Subcategory === groupId) {
        updatedKits[kitId] = { ...kit, Subcategory: undefined }
        affectedKitCount++
      }
    })

    const updatedKitsData: KitsData = {
      ...kitsData,
      _categories: {
        ...categories,
        [catId]: { ...category, subcategories: remainingGroups },
      },
      _kits: updatedKits,
    }

    await prisma.kitConfig.update({
      where: { id: idParsed.data.id },
      data: { kitData: stringifyKitData(updatedKitsData) },
    })

    // SECURITY: Audit logged
    await auditDelete(
      'kitGroup',
      `${idParsed.data.id}:${catId}:${groupId}`,
      authResult.context,
      { groupId, catId, configId: idParsed.data.id, ...removedGroup, affectedKitCount },
      request
    )

    logger.admin.info('Kit group deleted', {
      configId: idParsed.data.id,
      catId,
      groupId,
      affectedKitCount,
      actor: authResult.context.actorId,
    })

    return NextResponse.json({ success: true, data: { affectedKitCount } })
  } catch (error) {
    logger.admin.error('Failed to delete kit group', error as Error)
    return NextResponse.json(
      { success: false, error: { code: 'INTERNAL_ERROR', message: 'Failed to delete kit group' } },
      { status: 500 }
    )
  }
}
