/**
 * Middleware - Route Protection
 *
 * PUBLIC ROUTES:
 * - Landing page (/) and static assets are publicly accessible
 * - Auth routes (/api/auth/*) for NextAuth callbacks
 *
 * PROTECTED ROUTES:
 * - All other routes require authentication
 * - Admin permission checks are done via /api/admin/verify-access
 *   (NOT in middleware - matches PayNow pattern)
 */

import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'
import { getToken } from 'next-auth/jwt'

// Routes that don't require authentication (prefix matching)
// Note: API routes handle their own auth via authenticateWithScope (Bearer tokens)
// or requireSession, so they bypass session-only middleware checks
const PUBLIC_PATH_PREFIXES = [
  '/auth',
  '/api/auth',
  '/api/public',
  '/api/kits',
  '/api/analytics',
  '/api/telemetry',
  '/api/servers',
  '/api/identifiers',
  '/api/redirect',
  '/api/items',
  '/api/skins',
  '/api/events',
  '/api/lootmanager/download',
  '/_next',
  '/logos',
]

// Exact paths that don't require authentication
const PUBLIC_EXACT_PATHS = [
  '/',
  '/favicon.ico',
  '/logo.png',
  '/leaderboards',
]

// Production domain patterns for hostname detection
const PRODUCTION_DOMAINS = ['icefuse.com', 'icefuse.net', 'ifn.gg']

// NextAuth secrets (must match auth server)
const DEV_NEXTAUTH_SECRET = '2091cb9f77c7305308a6fc3d22f6c45ddbe70800dff5968241c2b26741a6d072'
const PROD_NEXTAUTH_SECRET = 'cae76e544c394d0dd7b0f9a5f809d7944e25091f371581139aa42ec75353eb10'

// App name for cookie naming (must match @icefuse/auth config)
const APP_NAME = 'kits'

/**
 * Check if hostname is a production domain
 */
function isProductionHostname(hostname: string): boolean {
  const normalizedHost = hostname.toLowerCase()
  return PRODUCTION_DOMAINS.some(
    domain => normalizedHost === domain || normalizedHost.endsWith(`.${domain}`)
  )
}

/**
 * Get NextAuth secret based on request hostname
 */
function getNextAuthSecret(hostname: string): string {
  return isProductionHostname(hostname)
    ? PROD_NEXTAUTH_SECRET
    : DEV_NEXTAUTH_SECRET
}

/**
 * Get cookie name for session token
 * Must match the cookie names generated by @icefuse/auth package
 */
function getSessionCookieName(isProduction: boolean): string {
  const prefix = isProduction ? '__Secure-' : ''
  return `${prefix}icefuse-${APP_NAME}.session-token`
}

/**
 * Get the real hostname from request (handles reverse proxy)
 */
function getRealHostname(request: NextRequest): string {
  // Check X-Forwarded-Host first (set by reverse proxy like Traefik)
  const forwardedHost = request.headers.get('x-forwarded-host')
  if (forwardedHost) {
    // May contain multiple hosts, take the first one
    return forwardedHost.split(',')[0].trim().toLowerCase()
  }

  // Check Host header
  const hostHeader = request.headers.get('host')
  if (hostHeader) {
    // Remove port if present
    return hostHeader.split(':')[0].toLowerCase()
  }

  // Fallback to URL hostname
  return request.nextUrl.hostname.toLowerCase()
}

export async function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl
  const hostname = getRealHostname(request)

  // Allow public paths (exact matches or prefix matches)
  if (
    PUBLIC_EXACT_PATHS.includes(pathname) ||
    PUBLIC_PATH_PREFIXES.some(prefix => pathname.startsWith(prefix))
  ) {
    return NextResponse.next()
  }

  const isProduction = isProductionHostname(hostname)

  // Get the session token using hostname-based secret
  // Use the app-specific cookie name from @icefuse/auth package
  const token = await getToken({
    req: request,
    secret: getNextAuthSecret(hostname),
    secureCookie: isProduction,
    cookieName: getSessionCookieName(isProduction),
  })

  // If no token, redirect to signin page which initiates OIDC flow
  if (!token) {
    // RSC/prefetch requests use fetch() which can't follow cross-origin
    // redirects (CORS). Return 204 so Next.js falls back to browser navigation.
    if (request.headers.get('rsc') === '1' || request.headers.get('next-router-prefetch') === '1') {
      return new NextResponse(null, { status: 204 })
    }

    // Redirect to our signin page which calls signIn('icefuse')
    const signinUrl = new URL('/auth/signin', request.url)
    signinUrl.searchParams.set('callbackUrl', pathname)
    return NextResponse.redirect(signinUrl)
  }

  // User is authenticated - allow access
  // Admin permission checks are done via /api/admin/verify-access endpoint
  // This matches the PayNow pattern where admin checks happen at route/layout level
  return NextResponse.next()
}

export const config = {
  matcher: [
    /*
     * Match all request paths except:
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     */
    '/((?!_next/static|_next/image|favicon.ico).*)',
  ],
}
